openapi: 3.0.3
components:
  parameters:
    location:
      name: location
      in: path
      description: The physical organisation location of the thing like a terminal or harbor.
      schema:
        type: string
      required: true
    type:
      name: type
      in: path
      description: Type of the thing
      schema:
        type: string
      required: true
    name:
      name: name
      in: path
      description: The name of the thing.
      schema:
        type: string
      required: true